rotate-matrix: rotate-matrix.cc
	g++ -std=c++11 -o rotate-matrix rotate-matrix.cc

print-outer: print-outer.cc
	g++ -o print-outer print-outer.cc

1.5: 1.5.cc
	g++ -o 1.5 1.5.cc

1.4: 1.4.cc
	c++  -o0  -g -o 1.4 1.4.cc

clean:
	rm -rf 1.4 1.5 1.4.dSYM
